### ISSUE TITLE
打开cpu相关性会导致在战役里屏幕“冻结”

### ISSUE THREAD

**Issue by Alexius66** [SadPencil/Mo3RegUI#1]
有声音，游戏还在进行，但是画面是卡死的，手动在ddraw.ini里改成singlecpu=true就不会出现这种现象。

**Comment by SadPencil** [comment]
确实存在这种概率，较低，考虑到游戏本身也有莫名其妙崩溃的可能性，再增加一点崩溃概率换取性能应该还是值的

**Comment by Alexius66** [comment]
> 确实存在这种概率，较低，考虑到游戏本身也有莫名其妙崩溃的可能性，再增加一点崩溃概率换取性能应该还是值的

好的，原来是这样考虑的，那建议之后更新可以加个说明提醒下小白。

**Comment by SadPencil** [comment]
这种说明不是很好写，表述但凡有一点容易引起误解的地方就很麻烦，比如说因为看到过注册机的这行字，大家游戏崩溃后先手动改了这里，结果发现还是崩溃（其他原因崩溃概率更大），再去找别的原因。这样的话就不如压根不提了
