### ISSUE TITLE
谢谢你的开源！ Thanks for your opensource hard work!

### ISSUE THREAD

**Issue by Yonggie** [SadPencil/Mo3RegUI#3]
谢谢你的开源！ Thanks for your opensource hard work!
爱 来自 瓷器。 Love from China.

**Comment by Yonggie** [comment]
尝试了最新的红色警戒，体验太棒了！
Tried the latest RedAlert, such a nice experience!

**Comment by Yonggie** [comment]
尝试了最新的红色警戒，体验太棒了！
Tried the latest RedAlert, such a nice experience!

**Comment by SadPencil** [comment]
Thanks for the feedback
