### ISSUE TITLE
多功能车被打爆后，不会出现里面的运载的人

### ISSUE THREAD

**Issue by Yonggie** [SadPencil/Mo3RegUI#4]
reunion，原版。
盟军多功能车被打爆后里面的人也不见了。

**Comment by Yonggie** [comment]
win10系统

**Comment by SadPencil** [comment]
请向相关 mod 开发者反馈此 bug。

Close as unrelated.

**Comment by SadPencil** [comment]
如果你想反馈“重聚未来(重聚2023)”的相关bug，请联系作者 [君悦OwO](https://space.bilibili.com/471856024)。

本项目是为“心灵终结中文整合包”/《泰矿危机2：黎明坠落》服务的注册机程序，并不是 CnCNet 或心灵终结或其他 MOD 的一部分。
